# Site Settings
title: gsuveti's resume
url: 'http://webjeda.com'
baseurl: '/online-cv' #change it according to your repository name
about: True # set to False or comment line if you want to remove the "How to use?" in the sidebar


# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
#style: styles-2
#style: styles-3
#style: styles-4
#style: styles-5
style: styles-6
sass:
  sass_dir: assets/scss


#Profile information
name: George Suveti
tagline: Frontend developer
pic: profile.jpg  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below
summary: 'Frontend developer | ux/ui enthusiast <br><br>
Versatile Software Developer with 5+ years of experience designing,
developing, and managing complex enterprise and end-user applications. Specialized in Angular, React and responsive design.
Solid experience on mobile development in Android and ionic. Extensive knowledge with backend frameworks: expressJS, nodeJS or Spring '

#sidebar links
email: george.suveti@gmail.com
phone: 0040 740 561 805
#website: blog.webjeda.com #do not add http://
linkedin: gsuveti
github: gsuveti
twitter: '@gsuveti'
#Update all the sections by editing the files inside _data folder.

# uncomment the next line, if you want the education section displayed in main instead of the sidebar
#education_in_main: True

# Tracker
analytics: UA-83979019-1

# Build settings
encoding: "utf-8"
compress_html: # - http://jch.penibelst.de/
  clippings: all
  ignore:
    envs: development


gems:
  - jekyll-pdf
